### ISSUE TITLE
App Router Next.js example app

### ISSUE THREAD

**Issue by bizob2828** [newrelic/newrelic-node-examples#203]
## Is your feature request related to a problem? Please describe.
We need a workable Next.js application leveraging App Router. this application should show how data fetching occurs, and injecting browser agent.

Tasks:
 * Create a next.js example application using app router
 * Update README in next.js instrumentation to this new application
 * This application must contain the following
      * injecting browser agent
      * handling errors both server and client side
      * logging via pino/winston/bunyan(must externalize libraries in webpack, see https://github.com/newrelic/newrelic-node-nextjs/pull/175)
      * dynamic pages with data fetching via `app/lib/function`
      * static pages with `generateStaticPaths` and `getProps`
      * middleware
 

## Context
Our [test application](https://github.com/newrelic/newrelic-node-nextjs/tree/main/tests/versioned/app-dir) in versioned tests may be a good start

**Comment by jsumners-nr** [comment]
> static pages with generateStaticPaths and getProps

I'm pretty sure that's a "pages router" only feature. I can't find anything in the "app router" docs that relate to it.
