### ISSUE TITLE
New relic types not working when setting up browser agent in next app

### ISSUE THREAD

**Issue by alexchoiweb** [newrelic/newrelic-node-examples#230]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I'm setting up new relic browser agent for a next.js app following this example:

https://github.com/newrelic/newrelic-node-examples/blob/58f760e828c45d90391bda3f66764d4420ba4990/nextjs-app-router/app/layout.js

(forum topic https://forum.newrelic.com/s/hubtopic/aAXPh0000001rgbOAA)

But getting type errors even after adding `@types/newrelic`, anyone know what I'm missing?

## Additional context

![image](https://github.com/newrelic/newrelic-node-examples/assets/35116846/e29a668d-0f2a-42cc-905c-411998ada4fe)

![image](https://github.com/newrelic/newrelic-node-examples/assets/35116846/9b8e304f-5c41-43fa-b7dd-43a77e00f7b6)

![image](https://github.com/newrelic/newrelic-node-examples/assets/35116846/61eb5128-5bf5-462d-96b0-4b73df536e15)

[TIP]:  # ( Add any other context about the problem here. )

**Comment by jsumners-nr** [comment]
The referenced `@types/newrelic` package is a third party package maintained at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/newrelic

**Comment by jsumners-nr** [comment]
Given that the types package in question is not maintained by this team, I am closing this issue as not supported.
