### ISSUE TITLE
nextjs-legacy example does not work

### ISSUE THREAD

**Issue by eddie0329** [newrelic/newrelic-node-examples#293]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Run `yarn build` shows an error as below: 

> Restarted static page generation for /hello/world because it took more than 60 seconds

As well as yarn build, yarn dev shows infinite loading.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

```shell
# this pacakge was missing
yarn add react-dom
yarn dev
```

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

Build project without an timeout error.

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

ex: mac os Sonoma 14.2.1

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by jsumners-nr** [comment]
How is this a bug with the example? The example is effectively:

1. `cp .sample.env .env`
2. `# edit .env and add your key`
3. `npm run build`
4. `npm start`

**Comment by eddie0329** [comment]
Thank you for reply. 

I followed what you've said but same errors remain. 
I am assuming that following codes are suspicious.

```js
if (newrelic.agent.collector.isConnected() === false) {
      await new Promise((resolve) => {
        newrelic.agent.on("connected", () => {
             // ⭐️ no logs are printed here
             console.log("connected")
             resolve("connected")
         })
      })
}
```

Are there any suggestions for this error?

**Comment by jsumners-nr** [comment]
Please use `npm` for installing the dependencies.
