### ISSUE TITLE
Question: How come the .env.sample variables aren't really being used in the nextjs app router? Can I see the file where it is being used ?

### ISSUE THREAD

**Issue by mike-rambil** [newrelic/newrelic-node-examples#305]
### Can't seem to find the location where these variables are used to initialize the app.

![image](https://github.com/user-attachments/assets/a96d35b7-9b09-42d5-99b2-8210ce6307c3)

**Comment by jsumners-nr** [comment]
The `.env` file is loaded via the start script:

https://github.com/newrelic/newrelic-node-examples/blob/9415503f3bd78fa5d87a7214596d51c946199474/nextjs/nextjs-app-router/package.json#L5

**Comment by mike-rambil** [comment]
thanks, didn't notice that!
